services:
  server:
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile
    volumes:
      - broker-db:/data
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./
      dockerfile: ./cmd/worker/Dockerfile
    volumes:
      - broker-db:/data

volumes:
  broker-db:
    driver: local